version: '3.8'

services:

  app:
    image: spring-book-library
    container_name: spring-book-library
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379


  redis:
    image: redis:latest
    container_name: redisNew
    ports:
      - "6379:6379"


  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
