spring:
  application:
    name: Spring-BookLibrary

  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 6000

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

logging:
  level:
    org:
      springframework:
        web:
          cors: DEBUG
          servlet:
            DispatcherServlet: DEBUG
        security: DEBUG
        batch: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO
